---
title: "Final Project Data Memo"
author: "Elena Andrews"
date: "5/9/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Data Source

For my final project, I have decided to use data on police killings in America in 2015 from FiveThirtyEight. This data-set was used in their article "Where Police Have Killed Americans in 2015." It contains 34 variables and 467 observations. Each observation represents a different person who was murdered by the police in 2015. Variables include the name of the person who was killed, their age, gender, and race, as well as the month and day of their murder, the city and state they were murdered in, and demographic information about the census tract in which they were murdered, including median household income and unemployment rate among other things.

I obtained the data from the FiveThirtyEight github repository. The journalists and data-scientists at FiveThirtyEight in turn compiled this data from two different sources: the Guardian's data-base on police murders in the United States and the 2015 American Community Survey conducted by the United States Census Bureau.

**FiveThirtyEight GitHub Repository:** <https://github.com/fivethirtyeight/data/tree/master/police-killings>

**The Guardian's "The Counted: People Killed by police in the US":**

<https://www.theguardian.com/us-news/ng-interactive/2015/jun/01/the-counted-map-us-police-killings>

**2015 American Community Survey:**

<https://www.census.gov/acs/www/data/data-tables-and-tools/data-profiles/2015/>

## Why This Data

I chose this data because of it's relevance to the current social and political climate in America, and because of my own passion for social justice and police reform. Unfortunately, police brutality in America has a long history, stretching back to the era of slavery and persisting up until our very immediate present moment. Through visualizations using this data-set, I hope to illuminate a story about the enduring systemic racism and classism inherent to police violence in America, and the severity of police violence as a whole and the urgent need to address it. I also want to probe deeper and answer questions such as, are people from areas with lower average household incomes over-represented among those murdered by the police? Are those people from areas with lower rates of college graduation over-represented among those murdered by the police? In what region of America did police killings happen most frequently in 2015? Were more women or men murdered by the police in 2015? Answering these questions and unfolding this story of police brutality in America will hopefully raise awareness and bring the country closer to creating communities where all feel safe and welcome.

## Visualizing the Data

After considering the data and the story I would like to tell using it, a number of visualizations come to mind. The first visualization I would like to create is a map of the United States with points for each of the victims of police violence in 2015. This will be possible because each observation in the data-set comes with a latitude and longitude coordinate, though I may have to download additional data from either `tigris` or `raster` to create the background map of the country itself. It would be helpful to label a few of the points, and perhaps even color the points based on race. I would also like to create a histogram or density plot of the average household incomes of the Census tracts in which the individuals were murdered by the police, perhaps faceting by race. In addition, I want to create a bar-graph of race faceted by gender. I think it would also be interesting to create a few scatterplots, including one of the average household income of the Census tract in which the individuals were murdered by the percentage of the 25 and older population in that tract with a bachelors degree or higher. Finally, I would like to create a stacked bar-graph of the cause of a person's death by how/whether the person killed was armed.

## Potential Data Issues

I see no issues with this data set. The data has already been successfully downloaded from GitHub and read into R with little difficulty. There is no data-cleaning necessary, as the data is already cleaned. Since the people at FiveThirtyEight did combine data from the Guardian and the Census, though, I will need to take care to be clear about how I label my graphs, being explicit, for example, about the fact that `h_income` is NOT the income of the individual murdered but the average household income of their Census tract. This applies to other variables in this dataset taken from the Census.
