---
title: "Visualization Explanations"
author: "Elena Andrews"
date: "6/9/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Introduction

This document answers the following question for each of the graphs present in my Shiny app: 

> What is the core concept(s) or insight(s) into the data that you believe the visualization communicates?

### Map 

This visualization provides insight into *where* in the United States most police killings occurred in the first six months of 2015. Specifically, it shows that there is a concentration of deaths at the hands of the police in and around (in the outlying neighborhoods/suburbs of) large cities. Cities with the highest number of body counts include San Francisco, Los Angeles, Houston, Pheonix and New York City. Furthermore, the victims of police violence in and around large cities are more racially diverse than in areas outside of large cities. This is reflective of the more racially diverse nature of urban populations as compared to rural populations, which tend, in most regions of the United States, to be largely white. Finally, this graph also gives insight into the variation in racial identity of victims of police violence across different regions of the United States. For example, there is a much higher number of Hispanic/Latinx victims in the Southwest and West than there are in the Midwest and Northeast. Further, there appear to be a larger number of Black victims in the Southeast than in other regions of the United States. 

I decided to add two interactive elements into this tab of my app: one select bar in which the user can choose a region, which then changes the plot to showcase a map of that region, and another select bar in which the user can choose a city within the region they have selected, which changes the table to showcase information about the victims in that city. Being able to choose between regional maps allows the viewer to visualize spatially where the police murdered Americans in the first six months of 2015 without being overwhelmed by a map of the entire United States, in which it would likely be hard to clearly see the points themselves as the states would be smaller and thus there would be more overlapping/overplotting. Toggling back and forth between the regional maps (rather than printing all four at once) also saves space, and makes it easy to compare the contents of the maps. I decided to add a second widget where the user can select a city to display information about the victims in that city because I though it would make sense to have more detailed information about the victims, specifically name, age, gender, race, and date of death, to supplement the map. This way the user is seeing both the "large picture" via the map, and the "smaller picture," ie the more intimate details that give more life and humanness to the data, via the table. Also, I thought it would make sense to connect the two widgets, such that the only cities that will appear in the second select bar are those located inside the region selected in the first widget. That way viewers are only exploring cities within the region they can see in the present map.

### Bargraph of Race and Gender

This plot is a joint bar-graph, in which the user can select to either view the racial distribution of police murder victims in the first six months of 2015, or the gender distribution of victims. The bargraph of race shows that the most people murdered by the police in the first six months of 2015 were white. This was actually a surprise to me: I had assumed, given the systemic racism present in policing, that the majority of victims would be Black or another group of color, rather than white. The second bargraph, of gender, shows that men overwhelmingly outnumber women among police murder victims in the first six months of 2015. The choice of adding a select bar widget was so that users could easily switch back and forth between the two variables. It made sense to me to group these two plots together since they're both bargraphs. Also, having the select bar makes the tab look much cleaner than if both plots were printed separately.

### Histogram of Age

The plot displays the distribution of the ages of police murder victims in the first half of 2015. It communicates the fact that most victims of police violence are younger, largely between the ages of 20 and 45. There are fewer victims between the ages of 50 and 60, and even less above the age of 65. Thus the distribution of age is right skewed. For this plot, I added a slider-bar widget that controls the number of bins the histogram has. This widget also has an animate option. This widget allows the user to visualize the histogram with a number of different bins, which I think gives the user a more nuanced and accurate sense of the distribution of the variable than a static histogram.

### Scatterplot of Percentage of College Graduates in Census Tract Population by Median Household Income of Census Tract

### Bargraph of Cause of Death (by itself and with various different variables in the fill)


