---
title: "Visualization Explanations"
author: "Elena Andrews"
date: "6/9/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Introduction

This document answers the following question for each of the graphs present in my Shiny app: 

> What is the core concept(s) or insight(s) into the data that you believe the visualization communicates?

### Map 

This visualization provides insight into *where* in the United States most police killings occurred in the first six months of 2015. Specifically, it shows that there is a concentration of deaths at the hands of the police in and around (in the outlying neighborhoods/suburbs of) large cities. Cities with the highest number of body counts include San Francisco, Los Angeles, Houston, Pheonix and New York City. Furthermore, the victims of police violence in and around large cities are more racially diverse than in areas outside of large cities. This is reflective of the more racially diverse nature of urban populations as compared to rural populations, which tend, in most regions of the United States, to be largely white. Finally, this graph also gives insight into the variation in racial identity of the victims of police violence across different regions of the United States. For example, there is a much higher number of Hispanic/Latinx victims in the Southwest and West than there are in the Midwest and Northeast. Further, there appear to be a larger number of Black victims in the Southeast than in other regions of the United States. However, in all regions there are a large number of white victims.

I decided to add two interactive elements into this tab of my app: one select bar in which the user can choose a region, which then changes the plot to showcase a map of that region, and another select bar in which the user can choose a city within the region they have selected, which changes the table to showcase information about the victims in that city. Being able to choose between regional maps allows the viewer to visualize spatially where the police murdered Americans in the first six months of 2015 without being overwhelmed by a map of the entire United States. A map of the entire country would likely make it hard to clearly see the points themselves as the states would be smaller and thus there would be more overlapping/overplotting. Toggling back and forth between the regional maps (rather than printing all four at once) also saves space, and makes it easy to compare the contents of the different maps. I decided to add a second widget where the user can select a city, in order to display information about the victims in that city, because I though it would make sense to have more detailed information about the victims, specifically name, age, gender, race, and date of death, to supplement the map. This way the user is seeing both the "large picture" via the map, and the "smaller picture," ie the more intimate details that give more life and humanness to the data, via the table. Also, I thought it would make sense to connect the two widgets, such that the only cities that will appear in the second select bar are those located inside the region selected in the first widget. That way viewers are only exploring cities within the region they can see in the present map.

### Bargraph of Race and Gender

This plot is a joint bar-graph, in which the user can select to either view the racial distribution of police murder victims in the first six months of 2015, or the gender distribution of victims. The bargraph of race shows that the most people murdered by the police in the first six months of 2015 were white. This was actually a surprise to me: I had assumed, given the systemic racism present in policing, that the majority of victims would be Black or another group of color, rather than white. The second bargraph, of gender, shows that men overwhelmingly outnumber women among police murder victims in the first six months of 2015. The choice of adding a select bar widget was so that users could easily switch back and forth between the two variables. It made sense to me to group these two plots together since they're both bargraphs. Also, having the select bar makes the tab itself look much cleaner than if both plots were printed separately.

### Histogram of Age

The plot displays the distribution of the ages of police murder victims in the first half of 2015. It communicates the fact that most victims of police violence are younger, largely between the ages of 20 and 45. There are fewer victims between the ages of 50 and 60, and even less above the age of 65. Thus the distribution of age is right skewed. For this plot, I added a slider-bar widget that controls the number of bins the histogram has. This widget also has an animate option. This widget allows the user to visualize the histogram with a number of different bins, which I think gives the user a more nuanced and accurate sense of the distribution of the variable than a static histogram would.

### Scatterplot of Percentage of College Graduates in Census Tract Population by Median Household Income of Census Tract

This plot displays percent of the 25 and older population in the census tract in which the victim was killed with a BA or higher by the median household income of the census tractin which the victim was killed. It shows that there is a positive relationship between these two variables: ie as the median household income of the census tract increases, the percentage of 25 and older residents with a bachelors degree increases. There is also another aspect of this plot that is interactive: the size of the points of the scatterplot can, via radio buttons, be changed to represent either the percent of the census tract in which the victim died that is non-Hispanic white, the percent that is Black, and the percent that is Hispanic/Latinx. This interactive layer of the graph shows that census tracts with higher percentages of Black or Hispanic/Latinx folks generally have lower median household incomes and fewer college graduates. On the other hand, the census tracts with higher median household incomes and a higher percentage of college graduates tend to be those tracts with a larger percentage of white folks. On the whole, however, the plot shows that most of the victims were killed in poorer census tracts with lower median household incomes and a lower percentage of college graduates, a sign that there is a class bias to violent policing. 

### Density Plot of Census Tract Income by Race of Victim

This is a static density plot, not containing any interactive elements. It displays the distribution of median household incomes across the census tracts in which the victims were killed by the police by the race of the victim. This plot provides insight into the fact that victims who were Black, Native American, and Hispanic/Latino were largely killed by the police in poorer areas than victims who were White or Asian/Pacific Islander.

### Bargraph of Cause of Death (by itself and with various different variables in the fill)

This is an interactive bar graph, in which the user can select the fill variable, choosing either none, Armed, or Race. Having this interactive feature allows the user to visualize the distribution of cause of death by itself, as well as visualize the relationship between the victim's cause of death and either how the victim was armed, or their race. The first bar-graph shows that in the first 6 months of 2015, the cause of death for those who were killed by the police was overwhelmingly gunshots. 411 of the 467 total victims were killed by gunshots. Only 27 were killed by a taser, 14 died in custody, 12 were struck by a vehicle and 3 have an unknown cause of death. The second bargraph shows that, across all causes of death, most people killed by the police were armed in some manner, with the most common weapon being a firearm. However, about 30% of those victims who were struck by a vehicle or who died in custody were *not* armed, and about 25% of those victims who were killed by gunshot were not armed either. Finally, the third bar-graph shows that a majority of those victims who died in custody or who were shot by a taser were Black, while the majority of victims killed by a gunshot or struck by a vehicle were white. 